# Use root/example as user/password credentials
version: '3.1'

services:

  api:
    container_name: hotel-reservation-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
     - app-network
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - mongo-express
    env_file:
      - .env.compose
    command: "/api"


  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - app-network
  #    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/


networks:
  app-network:
    driver: bridge