version: "3.5"

services:
  api:
    container_name: hotel-reservation-api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    depends_on:
      - mongo
      - mongo-express
    ports:
      - "3000:3000"
    env_file:
      - .env.compose
    command: "/api"

  mongo_seeding:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    depends_on:
      - mongo
    command: "go run seed.go"

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - app-network
      - mongo-network
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - 8081:8081
    networks:
      - mongo-network
    depends_on:
      - mongo

networks:
  app-network:
    driver: bridge
  mongo-network:
     driver: bridge

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG